bind | split-window -h
bind - split-window -v
bind -n M-S-Left select-pane -L
bind -n M-S-Right select-pane -R
bind -n M-S-Up select-pane -U
bind -n M-S-Down select-pane -D
bind -n M-Right next-window
bind -n M-Left previous-window
set -g mouse on

bind r source-file ~/.tmux.conf
set -sg escape-time 0
