# disable_ligatures always
window_border_width 2.0
active_border_color #ebcb8b
map shift+alt+w close_window 
copy_on_select yes
cursor_blink_interval 0
scrollback_lines 1000
enable_audio_bell no
font_family      Iosevka
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 16.0

adjust_line_height  0
adjust_column_width 0

background              #fafafa
foreground              #2a2a2a
cursor                  #2a2a2a
color0                  #2a2a2a
color1                  #2a2a2a
color2                  #2a2a2a
color3                  #2a2a2a
color4                  #2a2a2a
color5                  #2a2a2a
color6                  #2a2a2a
color7                  #2a2a2a
color9                  #2a2a2a
color8                  #2a2a2a
color10                 #2a2a2a
color11                 #2a2a2a
color12                 #2a2a2a
color13                 #2a2a2a
color14                 #2a2a2a
color15                 #2a2a2a

